import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();

const readJson = async (relativePath) =>
  JSON.parse(await readFile(path.join(root, relativePath), 'utf8'));

const readText = async (relativePath) => readFile(path.join(root, relativePath), 'utf8');

test('changesets release config is wired for workspace package publishing', async () => {
  const rootPackage = await readJson('package.json');
  const config = await readJson('.changeset/config.json');
  const releaseWorkflow = await readText('.github/workflows/release.yml');

  assert.equal(existsSync(path.join(root, 'ferrflow.json')), false);
  assert.equal(rootPackage.devDependencies['@changesets/cli'], '2.31.0');
  assert.equal(rootPackage.scripts['release:version'], 'projen release:version');
  assert.equal(rootPackage.scripts['release:publish'], 'projen release:publish');
  assert.equal(rootPackage.scripts.release, 'npm run release:publish');
  assert.equal(rootPackage.scripts.changeset, 'changeset');

  assert.deepEqual(config, {
    $schema: 'https://unpkg.com/@changesets/config@3.1.1/schema.json',
    changelog: '@changesets/cli/changelog',
    commit: false,
    fixed: [],
    linked: [],
    access: 'public',
    baseBranch: 'main',
    updateInternalDependencies: 'patch',
    ignore: [],
    '//': '~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
  });

  assert.match(releaseWorkflow, /uses: changesets\/action@v1\.9\.0/);
  assert.match(releaseWorkflow, /version: npm run release:version/);
  assert.match(releaseWorkflow, /publish: npm run release:publish/);
  assert.match(releaseWorkflow, /NPM_CONFIG_PROVENANCE: "true"/);
  assert.doesNotMatch(releaseWorkflow, /FerrFlow/);
});
